### ISSUE TITLE
use.html doesn't work, but easy workaround -- also, dude, this stuff is amazing

### ISSUE THREAD

**Issue by SaganRitual** [queviva/darth-fader#1]
I think there's a problem in darth-faderScript.js; I changed use.html to use darth-fader.min.js and it works great. I tried to fix it and submit a pull request, but my JS is rusty. Anyway, what you've done here is totally amazing, thanks!

Also, Atom got really confused about spaces or something, maybe linefeeds, I couldn't figure it out. Thanks again!

**Comment by queviva** [comment]
los siento - this was sort of a junkyard, but I have redone this and some of the other things here - like clockwizz - so that they are more useable things for other people - I'll commit that in a bit - thanks for looking at all that

**Comment by queviva** [comment]
ok - use.html is werking now, and so is everythingelse - I don't think I got it done in time for all the clones that got made yesterday, but at least this version is better - it could still be made a little smaller - anyway, this issue is closed
